language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

dist: trusty

matrix:
  allow_failures:
    - php: nightly

before_install:
  - sudo apt-get update > /dev/null

install:
  # install Oracle JDK8
  - sh -c ./build/server/jdk8-install.sh
  # install gremlin-server
  - sh -c ./build/server/install.sh
  - composer global require "fxp/composer-asset-plugin:^1.2.0"
  - composer update "phpunit/phpunit"
  - composer install

script: vendor/bin/phpunit --configuration build/phpunit.xml

after_success:
  - sh -c ./build/deploy.sh

env:
  global:
    - GREMLINSERVER_VERSION="3.2.1"
    - GH_REF: "github.com/PommeVerte/PommeVerte.github.io.git"
    - secure: "QqbRsl8iQVjEqm6gthFhlRPo/niUjgk9KiDN0u+pWGu08tzoGhykggwybrmDlEgFUBvJkgqGvxoTAQ0B/GagzpadUM4HlJNP1SGhhllKeKax60opKJkWwdodoZQxIG9KahtL+P8utliCzSx8R467EVWkd7YWpKF56FxmGgrfNJyCnvFwSmu/Zkc7uJi+HwBLLiwxF+nU96eZKMyC+vIY6awInxxJjRaDQLyl9X3R9cDXbM1RLgWQpBZofyIyx9TI64TyTmTscrtdUlMaJxhyV1rJJFWPwKVUj+yIw3gR2rszUqwF4zjpVmblDiEaBgDv2Rwfftm0qpiLRz/s5Zt+2AB5p8TSXa2t545oMHe59nA4RcRlWSZyotXel46Nz2DAhoywRTqEt9S/ekJhis+dwOac8dPfbr3/RJIdYtPf6IPHAIed1sAJtpmGCXjkAY3iFbooiaKqAckwYtO8eJDhKZ7/MkmQr/IfTRl9RD9KjSqsolM3337O3C5YEstq8EVDKXPyOKPC0qxeIa641XweVitOlm9jUANK7eDZAsPSM0/WEqKgw0/OCjK6WtXwx45DR12JtURCF6GYPBQkKgH+X/bLcP7EzK0myXpSjCS4bcaBSqfJCadhX3Kny267IVrx/wUWOeJCumixpzmf7xbQIoxvIe+hE1pCpUm+Kif1tLU="
